use veterinariaentrega;

-- TRIGGERS
-- TABLA PARA MOSTRAR CAMBIOS EN LA TABLA CLIENTES
DROP TABLE IF exists LOG_AUDITORIA;
CREATE TABLE IF NOT exists LOG_AUDITORIA
(ID_LOG INT auto_increment,
NOMBRE_DE_ACCION varchar(10),
NOMBRE_TABLA varchar(50),
USUARIO varchar(100),
FECHA_UPD_INS_DEL DATE,
primary key(ID_LOG)
);

/* TABLA PARA MOSTRAR CAMBIOS EN LA TABLA CLIENTES MOSTRANDO USUARIO, FECHA Y HORA DE CUANDO SE HIZO CAMBIO 
Y TRES CAMPOS IMPORTANTES DE LA TABLA CLIENTES */
drop table if exists LOG_AUDITORIA_2;
CREATE TABLE IF NOT exists LOG_AUDITORIA_2
(ID_LOG int auto_increment,
NOMBRE varchar(50),
APELLIDOS varchar(50),
TELÉFONO varchar(15),
NOMBRE_DE_ACCION VARCHAR (10),
NOMBRE_TABLA VARCHAR (50),
USUARIO VARCHAR(50),
FECHA_UPD_INS_DEL DATE,
HORA time,
PRIMARY KEY (ID_LOG)
);

/*TRIGGER PARA DETETAR CAMBIOS POSTERIOR A UN INSERT EN LA TABLA CLIENTES PARA LA TABLA AUDITORIA*/
DELIMITER $$
CREATE trigger TRG_LOG_CLIENTES AFTER INSERT ON CLIENTES
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA (NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL)
VALUES ('INSERT', 'CLIENTES', current_user(), now());
END$$
DELIMITER ;

/*TRIGGER PARA DETECTAR CAMBIOS POSTERIOR A UN INSERT EN LA TABLA CLIENTES PARA LA TABLA AUDITORIA_2 
(ESTA TABLA ES MÁS COMPLETA)*/
DROP trigger IF exists TRG_LOS_CLIENTES_2;
DELIMITER //
CREATE trigger TRG_LOS_CLIENTES_2 AFTER INSERT ON CLIENTES
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA_2 (NOMBRE, APELLIDOS, TELÉFONO, NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL,HORA)
VALUES (NEW.NOMBRE, NEW.APELLIDOS, NEW.TELÉFONO, 'INSERT', 'CLIENTES', current_user(), now(), current_time());
END//
DELIMITER ;

SELECT * FROM LOG_AUDITORIA;
SELECT * FROM LOG_AUDITORIA_2;
SELECT * FROM CLIENTES;

INSERT INTO CLIENTES(ID_CLIENTE, NOMBRE, APELLIDOS, E_MAIL, DIRECCIÓN, CIUDAD, ESTADO, CP, TELÉFONO, FECHA_DE_NACIMIENTO)
VALUES (17, 'ENRIQUE', 'LOPEZ LOPEZ', 'LOPEZLOPEZ@HOTMAIL.COM', 'AVENIDA SUR 877', 'RAMOS ARIZPE', 'COAHUILA', 63304, 8422781415, 19890102);

/*TRIGGER PARA DETECTAR CAMBIOS DE UN UPDATE EN LA TABLA CLIENTES PARA LA TABLA AUDITORIA_2*/
DROP TRIGGER IF exists TRG_LOG_CLIENTES_3
DELIMITER //
CREATE TRIGGER TRG_LOG_CLIENTES_3 BEFORE UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA_2(NOMBRE, APELLIDOS, TELÉFONO, NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL,HORA)
VALUES ( CONCAT(OLD.NOMBRE, '-', NEW.NOMBRE), CONCAT(OLD.APELLIDOS, '-', NEW.APELLIDOS), OLD.TELÉFONO, 'UPDATE','CLIENTES',current_user(), now(),current_time());
END//
DELIMITER ;

SELECT * FROM CLIENTES;
update CLIENTES SET NOMBRE = 'CAROLINA' WHERE ID_CLIENTE = 5;
SELECT * FROM LOG_AUDITORIA_2;

/* TABLA PARA MOSTRAR CAMBIOS EN LA TABLA MASCOTAS MOSTRANDO USUARIO, FECHA Y HORA DE CUANDO SE HIZO CAMBIO 
Y DOS CAMPOS IMPORTANTES DE LA TABLA MASCOTAS */
SELECT * FROM MASCOTAS;
drop table if exists LOG_AUDITORIA_3;
CREATE TABLE IF NOT exists LOG_AUDITORIA_3
(ID_LOG int auto_increment,
NOMBRE_MASCOTA varchar(350),
PROPIETARIO varchar(350),
NOMBRE_DE_ACCION VARCHAR (10),
NOMBRE_TABLA VARCHAR (50),
USUARIO VARCHAR(50),
FECHA_UPD_INS_DEL DATE,
HORA time,
PRIMARY KEY (ID_LOG)
);

/*TRIGGER PARA DETECTAR CAMBIOS POSTERIOR A UN INSERT EN LA TABLA MASCOTAS PARA LA TABLA AUDITORIA_3*/
DROP trigger IF exists TRG_LOG_MASCOTAS;
DELIMITER //
CREATE trigger TRG_LOG_MASCOTAS AFTER INSERT ON MASCOTAS
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA_3 (NOMBRE_MASCOTA, PROPIETARIO,NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL,HORA)
VALUES (NEW.NOMBRE_MASCOTA, NEW.PROPIETARIO,'INSERT', 'MASCOTAS', current_user(), now(), current_time());
END//
DELIMITER ;

SELECT * FROM LOG_AUDITORIA_3;

INSERT INTO MASCOTAS(ID_MASCOTA, NOMBRE_MASCOTA, RAZA, SEXO_MASCOTA, COLOR, EDAD, TAMANO, PESO, PEDIGREE, CHIP, DESCRIPCIÓN, FECHA_DE_NACIMIENTO,ID_CLIENTE,PROPIETARIO)
VALUES (16, 'PATO', 'Antiguo Pastor Ingles', 'M', 'Gris con blanco',5,63,13,'FCMV0619-D',1400317416, 'Goza de buena salud', 20230101, 2,'Ezequiel Ulloa Montes');

/*TRIGGER PARA DETECTAR CAMBIOS DE UN UPDATE EN LA TABLA MASCOTAS PARA LA TABLA AUDITORIA_3*/
DROP TRIGGER IF exists TRG_LOG_MASCOTAS_2
DELIMITER //
CREATE TRIGGER TRG_LOG_MASCOTAS_2 BEFORE UPDATE ON MASCOTAS
FOR EACH ROW
BEGIN
INSERT INTO LOG_AUDITORIA_3 (NOMBRE_MASCOTA, PROPIETARIO,NOMBRE_DE_ACCION, NOMBRE_TABLA, USUARIO, FECHA_UPD_INS_DEL,HORA)
VALUES ( CONCAT('ANTIGUO_NOMBRE: ', OLD.NOMBRE_MASCOTA, ' - NUEVO_NOMBRE: ', NEW.NOMBRE_MASCOTA), CONCAT('ANTIGUO_PROPIETARIO: ',OLD.PROPIETARIO, ' - NUEVO_PROPIETARIO: ', NEW.PROPIETARIO),'UPDATE','MASCOTAS',current_user(), now(),current_time());
END//
DELIMITER ;

SELECT * FROM MASCOTAS;
update MASCOTAS SET PROPIETARIO = 'Catalina Herrera Ulloa' WHERE ID_CLIENTE = 3;
update MASCOTAS SET NOMBRE_MASCOTA = 'SUSY' WHERE ID_MASCOTA=4;
SELECT * FROM LOG_AUDITORIA_3;






 



 


 


